### ISSUE TITLE
Programatically add SVG element?

### ISSUE THREAD

**Issue by uncleramsay** [chrvadala/react-svg-pan-zoom#116]
Hi,

The code examples in the documentation all have an `<svg>` element in the markup of the `render` function. However, in my use case I am generating the SVG elements programatically after the page has rendered.

Is there a way to programatically update the SVG contained inside the viewer?

Thanks

**Comment by chrvadala** [comment]
I think that this issue could help you https://github.com/chrvadala/react-svg-pan-zoom/issues/44
