### ISSUE TITLE
Required prop types warnings

### ISSUE THREAD

**Issue by psixdev** [chrvadala/react-svg-pan-zoom#117]
When I zoom with gestures on the touchscreen, I get errors in the console (I use chrome devtools with my phone as remote device):
```
Warning: Failed prop type: The prop `startX` is marked as required in `be`, but its value is `null`.
Warning: Failed prop type: The prop `startY` is marked as required in `be`, but its value is `null`.
Warning: Failed prop type: The prop `endX` is marked as required in `be`, but its value is `null`.
Warning: Failed prop type: The prop `endY` is marked as required in `be`, but its value is `null`.
```

This problem is repeated in the example:
https://jsfiddle.net/chrvadala/f67qyfsd/

![image](https://user-images.githubusercontent.com/6077446/40486860-25039402-5f6b-11e8-8612-81047d58e3ea.png)

**Comment by chrvadala** [comment]
Fixed with v3.1
