### ISSUE TITLE
Hide tool controls?

### ISSUE THREAD

**Issue by GarrettFleischer** [chrvadala/react-svg-pan-zoom#119]
### Features:
Is it possible to hide the tool controls and default the behavior to the "auto" tool?

**Comment by chrvadala** [comment]
Sure,
you can set up the props `tool="auto"` and `miniaturePosition="none"`

Any available props is available here https://github.com/chrvadala/react-svg-pan-zoom/blob/master/docs/documentation.md#available-props

**Comment by GarrettFleischer** [comment]
Awesome, thanks!
