### ISSUE TITLE
Remove console info on instantiation

### ISSUE THREAD

**Issue by colinmegill** [chrvadala/react-svg-pan-zoom#12]
![image](https://cloud.githubusercontent.com/assets/1770265/20229188/eb474f8e-a809-11e6-89d8-91c0d7c76335.png)

Hi there! Could you remove (or add a `silent={true}` flag) on the console that logs every time? Great work on 2.0 release! Lots of great additions.

**Comment by chrvadala** [comment]
Hi @colinmegill when I added this console message I was inspired by a lot of great libraries like Potree and Three.js
I thought that it will not annoyed anybody, but maybe that i was wrong.
I will remove this console message Monday. 
Thank you for your feedback.

**Comment by chrvadala** [comment]
released with version 2.1
