### ISSUE TITLE
loading a svg via file

### ISSUE THREAD

**Issue by nufaylr** [chrvadala/react-svg-pan-zoom#130]
Hi, is it possible to load a svg via file (exported one from Adobe illustrator) ? or either using dangerouslySetInnerHTML..

**Comment by nufaylr** [comment]
implemented under #131 example :

```
<ReactSVGPanZoom
          style={{border: "1px solid black"}}....  **svgContain={props.SvgContent}**>
            <svg width={800} height={800} xmlns="http://www.w3.org/2000/svg" xlinkHref="http://www.w3.org/1999/xlink" />
 </ReactSVGPanZoom>
```

**Comment by levaifelasticad** [comment]
Hi, there is any chance to merge this in master ?

**Comment by levaifelasticad** [comment]
Thanks. Sorry, but I'm new in React. How can I use your version in my production ? I added the project with yarn, but the code is from master branch. If I modify the viewer.js the min file remains the same. Somehow I have to build it, but I don't know how to do this.

**Comment by levaifelasticad** [comment]
Thanks a lot. It works with yarn command.

**Comment by levaifelasticad** [comment]
I still have problems. After I add with yarn your version, I have this : Module not found: Error: Can't resolve 'react-svg-pan-zoom' when I use import { ReactSVGPanZoom } from 'react-svg-pan-zoom'.

**Comment by levaifelasticad** [comment]
Unable to resolve path to module 'react-svg-pan-zoom'.eslint(import/no-unresolved)
Missing file extension for "react-svg-pan-zoom"eslint(import/extensions)
module "/Users/.../Library/Caches/typescript/3.2/node_modules/@types/react-svg-pan-zoom/index"

**Comment by nufaylr** [comment]
😞not the correct solution but try to install from my build branch 
'npm install github:nufaylr/react-svg-pan-zoom#npmbuild' or yarn add

**Comment by levaifelasticad** [comment]
Warning: Failed prop type: `ReactSVGPanZoom` should have a single child of the following types:  `svg`.
I use this code:
render() {
        return (
            <div className={styles.stageCurrentFrame}>
                <div
                    onClick={this.onStageClick}
                    role="presentation"
                >
                    <ReactSVGPanZoom
                        svgContain={this.props.svgString}
                        width={500}
                        height={500}
                        detectAutoPan={false}
                        toolbarPosition={'left'}
                        miniaturePosition={'left'}
                    />
                </div>
            </div>
        );
    }

where this.props.svgString is a string containing an svg like
"<svg ...>"

**Comment by levaifelasticad** [comment]
"<svg width="256" height="255" viewBox="0 0 256 255" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" id="el_gf4-YOgI0"><style>#el_gf4-YOgI0 *{animation-duration: 3s;animation-delay: 0s;animation-iteration-count: infinite;animation-play-state: paused;animation-timing-function: cubic-bezier(0, 0, 1, 1);}#el_lFXzNSI_dq{fill: #87C040;}#el_KU5ao7XKf2{fill: #87C040;}#el_Ww6Gq0xqnI{fill: #87C040;}#el_HWAgeNTQj8{fill: #87C040;}#el_Jm1JR-EfIn{fill: #ED9A2D;}#el_XYTmXoMJUk{fill: #5698C6;}#el_dWzvMlaEqv{fill: #5698C6;}#el_yr7tnFd8L8{fill: #5698C6;}#el_bmZPQ_UtJQ{fill: #446BA6;}#el_4lpqgBIPko{fill: #446BA6;}#el_Og6DLndRv3{fill: #446BA6;}#el_acxsjncJzc{fill: #FFF101;}#el_MY7_skBsTs{fill: #45AB47;}#el_fpJ0wMDzvj{fill: #45AB47;}#el_cIaAM38I-Kn{fill: #45AB47;}#el_nQ_Ut-QY97m{fill: #45AB47;}</style>
	<g id="el_FbE02_smQx">
		<path d="M88.9565187,166.907984 L121.256108,134.606322 L72.7528359,134.608395 L72.6367696,134.608395 C45.7591337,134.608395 23.9697609,156.397767 23.9697609,183.273331 C23.9697609,210.153039 45.7570611,231.94034 72.634697,231.94034 C74.6762201,231.94034 76.6845814,231.799402 78.6597809,231.554834 C68.037643,210.62974 71.4615985,184.400832 88.9565187,166.907984" id="el_lFXzNSI_dq"/>
		<path d="M128.336152,183.213225 L128.336152,137.534923 L94.0406366,171.834584 L93.9577321,171.915416 C74.9518775,190.92127 74.9518775,221.734797 93.9577321,240.740651 C112.963587,259.746506 143.777113,259.746506 162.782968,240.740651 C164.225506,239.298113 165.520889,237.766453 166.745802,236.199558 C144.44864,228.906035 128.338224,207.94778 128.336152,183.213225" id="el_KU5ao7XKf2"/>
		<path d="M167.713712,166.897621 L135.414123,134.598032 L135.414123,183.21737 C135.414123,210.097079 157.203496,231.884379 184.081131,231.884379 C210.958767,231.884379 232.74814,210.097079 232.74814,183.219443 C232.74814,181.17792 232.607203,179.169559 232.362634,177.194359 C211.437541,187.81857 185.208633,184.392541 167.713712,166.897621" id="el_Ww6Gq0xqnI"/>
		<path d="M241.546379,93.0732448 C240.103841,91.6307066 238.574253,90.335324 237.007358,89.1104101 C229.713836,111.4055 208.753508,127.517988 184.021026,127.517988 L138.344796,127.517988 L172.721144,161.896408 C191.726998,180.902262 222.542597,180.902262 241.546379,161.896408 C260.552234,142.890553 260.552234,112.077027 241.546379,93.0732448" id="el_HWAgeNTQj8"/>
		<path d="M184.027244,23.1080724 C181.98572,23.1080724 179.977359,23.2469374 178.00216,23.4915056 C188.624298,44.4186717 185.200342,70.6455074 167.705422,88.1404276 L135.407905,120.440017 L184.027244,120.440017 C210.902807,120.440017 232.69218,98.6506444 232.69218,71.7730085 C232.694252,44.8953725 210.904879,23.1080724 184.027244,23.1080724" id="el_Jm1JR-EfIn"/>
		<path d="M162.704208,14.305688 C143.698354,-4.69809386 112.884827,-4.69809386 93.8789728,14.3077607 C92.4385073,15.7502988 91.1431246,17.2798867 89.9182108,18.8488541 C112.213301,26.1423767 128.325789,47.100632 128.325789,71.8331142 L128.325789,117.511416 L162.621304,83.2138282 L162.704208,83.1329963 C181.710063,64.1271418 181.710063,33.3136152 162.704208,14.305688" id="el_XYTmXoMJUk"/>
		<path d="M88.9958983,88.1735894 L90.3804033,89.6182001 L121.214656,120.452453 L121.247818,120.452453 L121.247818,71.9450353 L121.247818,71.828969 C121.247818,44.9513331 99.458445,23.1619603 72.5808091,23.1619603 C45.7031732,23.1619603 23.9138004,44.9492605 23.915873,71.8268964 C23.915873,73.8642743 24.054738,75.8664177 24.2972336,77.837472 C45.2368354,67.2215519 71.4989055,70.6765966 88.9958983,88.1735894" id="el_dWzvMlaEqv"/>
		<path d="M19.7975924,165.515189 C20.1789531,164.383543 20.5893303,163.268477 21.0390872,162.169993 C21.0950477,162.031128 21.1447904,161.89019 21.2028235,161.75547 C21.6961052,160.574081 22.2391297,159.423781 22.809098,158.28799 C22.9334548,158.037204 23.0619567,157.790563 23.1925313,157.539777 C23.7790806,156.412276 24.396719,155.303428 25.0558097,154.223597 C25.1262786,154.107531 25.2029652,153.997682 25.273434,153.885761 C25.8993629,152.876399 26.5605262,151.896054 27.2486335,150.932289 C27.3895712,150.733318 27.5284362,150.532275 27.673519,150.335377 C28.4134416,149.328087 29.1844534,148.349814 29.9865543,147.396412 C30.1502907,147.201587 30.3160997,147.012979 30.4839813,146.824371 C31.2674287,145.916567 32.0757475,145.031562 32.9151555,144.177646 C32.9897695,144.103031 33.0581657,144.024272 33.1327798,143.949658 C34.0260756,143.052217 34.9566786,142.194156 35.9080076,141.360965 C36.1152688,141.178576 36.32253,140.998258 36.5318639,140.820014 C37.4894108,140.003404 38.4697564,139.217884 39.4791185,138.465526 C39.6117657,138.368113 39.7506307,138.276918 39.8832779,138.181578 C40.8263165,137.495544 41.7921538,136.840598 42.7787173,136.212597 C42.9735428,136.08824 43.1662958,135.959738 43.3631939,135.837454 C44.4285166,135.178363 45.5187107,134.558652 46.6296309,133.97003 C46.8638361,133.847746 47.1001139,133.729607 47.3363917,133.609396 C48.4452392,133.043572 49.5685951,132.502621 50.7168223,132.011412 C50.7727828,131.988613 50.8266707,131.961669 50.8826312,131.936797 C52.0702381,131.433153 53.2847889,130.983396 54.5138479,130.560583 C54.7791423,130.469388 55.0423641,130.378193 55.3097311,130.291143 C56.5263545,129.895274 57.7595588,129.530495 59.0114166,129.213385 C59.2020969,129.167787 59.3989951,129.126335 59.5896754,129.08281 C60.7503383,128.803008 61.9234368,128.562585 63.108971,128.357396 C63.3307405,128.320089 63.5504374,128.274492 63.772207,128.24133 C65.0592992,128.034069 66.3629723,127.878623 67.6770085,127.762556 C67.9609564,127.737685 68.2469769,127.719031 68.5309247,127.696233 C69.8905584,127.59882 71.2564099,127.530424 72.6409149,127.530424 L118.319217,127.528351 L83.940797,93.1499314 C64.9349424,74.1461495 34.1193432,74.1440769 15.1155613,93.1499314 C-3.89029323,112.155786 -3.89029323,142.969313 15.1155613,161.975167 C16.5560268,163.415633 18.0648886,164.74625 19.6297108,165.969091 C19.6815261,165.815718 19.7457771,165.668562 19.7975924,165.515189" id="el_yr7tnFd8L8"/>
		<path d="M84.0547906,93.1499314 L111.274408,120.369548 L74.6886558,120.369548 L72.6139709,120.413073 C50.333389,120.413073 31.5513766,105.440522 25.7770788,85.0087104 C44.3124503,74.6145599 68.2055246,77.302738 83.9739588,93.0690996 L84.0547906,93.1499314" id="el_bmZPQ_UtJQ"/>
		<path d="M121.229164,71.8186059 L121.229164,110.313234 L95.358818,84.4428873 L93.8623919,83.006567 C78.1063934,67.2526411 75.4119975,43.3823656 85.7771314,24.8532119 C106.233815,30.6109288 121.229164,49.4074495 121.229164,71.7025397 L121.229164,71.8186059" id="el_4lpqgBIPko"/>
		<path d="M162.853437,83.0956893 L135.63382,110.317379 L135.63382,73.7316271 L135.590295,71.6569422 C135.590295,49.3763603 150.562846,30.5922753 170.994658,24.8200501 C181.388808,43.3554216 178.70063,67.2484959 162.934268,83.0148574 L162.853437,83.0956893" id="el_Og6DLndRv3"/>
		<path d="M183.996154,120.338459 L145.501527,120.338459 L171.371873,94.4681128 L172.808193,92.9716868 C188.562119,77.2156883 212.432395,74.5212923 230.961548,84.8864263 C225.203831,105.343109 206.407311,120.338459 184.112221,120.338459 L183.996154,120.338459" id="el_acxsjncJzc"/>
		<path d="M172.627876,161.703655 L145.408259,134.484038 L181.994011,134.484038 L184.068696,134.440513 C206.349278,134.442586 225.13129,149.415137 230.905588,169.846949 C212.368144,180.239026 188.477142,177.552921 172.708708,161.784487 L172.627876,161.703655" id="el_MY7_skBsTs"/>
		<path d="M135.526044,182.993528 L135.526044,144.4989 L161.39639,170.369247 L162.894889,171.805567 C178.648815,187.561566 181.343211,211.427696 170.978077,229.958922 C150.521394,224.201205 135.526044,205.406757 135.526044,183.107522 L135.526044,182.993528" id="el_fpJ0wMDzvj"/>
		<path d="M94.1587755,171.946505 L121.378392,144.724815 L121.378392,181.310567 L121.421917,183.385252 C121.421917,205.665834 106.449366,224.449919 86.0175545,230.224217 C75.6234039,211.6847 78.311582,187.793698 94.0779436,172.027337 L94.1587755,171.946505" id="el_cIaAM38I-Kn"/>
		<path d="M72.8046512,134.685081 L111.299279,134.685081 L85.4289326,160.555428 L83.9926123,162.051854 C68.2366138,177.807852 44.3684109,180.502248 25.8371846,170.137114 C31.5969741,149.678359 50.3914221,134.685081 72.6885849,134.685081 L72.8046512,134.685081" id="el_nQ_Ut-QY97m"/>
	</g>
</svg>"

**Comment by nufaylr** [comment]
this.props.svgString can be called via ajax. example like this

``` 
fetch('your-file-path/foo.svg').then(r => r.text()).then((svg)=>{
     this.setState({
          SvgContent: svg
     })
}) 
```

**Comment by levaifelasticad** [comment]
Hi again!
I added your builded version and it's working in my project with my local version. But how I can use it in production ? 
I'm not sure if I understand exactly the flow. If I add with yarn the project 
yarn add react-svg-pan-zoom
it will add to my project the owner's version from npm register, and also make a build of the project.
But if I add it from your github repository , the build doesn't start.
So, what should I do to have a built version from your github repository and to use it in our production ?

**Comment by levaifelasticad** [comment]
What will happen when yarn will update the packages ? It will update from the base project ?

**Comment by chrvadala** [comment]
Hi guys,
sorry for my late answer.
I understand that load a SVG dynamically is a quite common requirement.
I had also some other issues here https://github.com/chrvadala/react-svg-pan-zoom/issues/44 and here https://github.com/chrvadala/react-svg-pan-zoom/issues/116

I watched the solution proposed by nufaylr in his PR https://github.com/chrvadala/react-svg-pan-zoom/pull/131 and I think that isn't so safe to use `dangerouslySetInnerHTML` in a component like react-svg-pan-zoom, that is used by a lot of users. Someone could say that I may document well it, but in the end who read the documentation? 😄  I'm concerned about users that may use that feature and expose their project to XSS attack (as documented here https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml).

A better way could be to **parse** the SVG and include it in a safer way.
My idea is to have something like this (or similar)
```javascript
<ReactSvgPanZoomLoader src="image.svg">
{ ({width, height, content}) => (
       <ReactSVGPanZoom width={500} height={500}>
             <svg width={width} height={height}>
                  {content}
             </svg>  
       </ReactSVGPanZoom>
)
</ReactSvgPanZoomLoader>
```
Unfortunately actually the only available way is https://github.com/chrvadala/react-svg-pan-zoom/issues/44#issuecomment-310012989 (that uses the dangerous React feature)

**Comment by nufaylr** [comment]
Hi there, 
If you add it from `github:nufaylr/react-svg-pan-zoom#npmbuild` then it will **not keep a recode** of owner's version, you can see it under the package.json. so when you do build it will take it from `github:nufaylr/react-svg-pan-zoom#npmbuild`. :) in theory not the correct solution, i may ⛔️delete the repository in future then the build will fail :(.  maybe you can take a fork from my repository and change into your repository. example like this replace <gitusername> with your github username `github:**<gitusername>**/react-svg-pan-zoom#npmbuild` and run a build. so its your own copy. 

The best solution will be the library author to respond on the merge request or either publish the library into NPM register under different name.

**Comment by nufaylr** [comment]
Hi Christian, Thank you for making this library :) . Yes i do agree `dangerouslySetInnerHTML` it self dangerous. and your suggestion idea looks safe.. just a thought maybe we might stuck in with parsing SVG, usually SVG dom tree is massive and styles etc.. 

 I'm happy to run a test on your idea. i will update the ticket soon.

**Comment by levaifelasticad** [comment]
Hi guys,

Unfortunately, in my case it doesn't work, the svg doesn't load. My string includes the whole svg structure, with svg tag too, probably this is the problem.

**Comment by levaifelasticad** [comment]
Hi guys,
Thanks a lot, with #44 it's working now.

**Comment by chrvadala** [comment]
Hi guys, I found this interesting post https://stackoverflow.com/a/5451238 about SVG inclusion. Tomorrow I'll perform some experiments, because I agree with nufaylr that parsing could be challenging. I hope that we'll find a good solution :)

**Comment by levaifelasticad** [comment]
Hi guys,

I had an another error, and doesn't figure out what I do wrong:

I tried to use ref, but I had this error:

Cannot read property 'zoomOnViewerCenter' of null at render.

Here' s my code:

import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { ReactSVGPanZoom } from 'react-svg-pan-zoom';
import { AutoSizer } from 'react-virtualized';
import StageHandler from '../StageHandler/StageHandler.container';
import styles from './View.scss';

class View extends Component {
    constructor(props, context) {
        super(props, context);
        this.Viewer = null;
    }

    componentDidMount() {
        this.props.resetHandlebarPosition();
        this.Viewer.fitToViewer();
    }

    onStageClick = (ev) => {
        ev.stopPropagation();
        const { target: { id } } = ev;
        this.props.setElement(id);
    };

    render() {
        const { width: svgwidth, height: svgheight } = this.props.projectDimensions;
        return (
            <div
                className={styles.stageView}
                onClick={this.onStageClick}
                role="presentation"
            >
                <button className="btn" onClick={this.Viewer.zoomOnViewerCenter(1.1)}>Zoom in</button>
                <button className="btn" onClick={this.Viewer.fitSelection(40, 40, 200, 200)}>Zoom area 200x200</button>
                <button className="btn" onClick={this.Viewer.fitToViewer()}>Fit</button>
                <AutoSizer>
                    {(({ width, height }) => width === 0 || height === 0 ? null : ( // eslint-disable-line
                        <ReactSVGPanZoom
                            width={width}
                            height={height}
                            ref={(Viewer) => { this.Viewer = Viewer; }}
                            detectAutoPan={false}
                            toolbarPosition={'left'}
                            miniaturePosition={'left'}
                            toolbarProps={{ SVGAlignX: 'center', SVGAlignY: 'center' }}
                            background={'#f1f3f2'}
                        >
                            <svg
                                width={svgwidth}
                                height={svgheight}
                                xmlns="http://www.w3.org/2000/svg"
                                xlinkHref="http://www.w3.org/1999/xlink"
                            >
                                <g
                                    dangerouslySetInnerHTML={{ // eslint-disable-line
                                        __html: this.props.svgString,
                                    }}
                                />
                            </svg>
                        </ReactSVGPanZoom>
                    ))}
                </AutoSizer>
                <StageHandler />
            </div>
        );
    }
}

View.propTypes = {
    svgString: PropTypes.string,
    projectDimensions: PropTypes.object, // eslint-disable-line
    setElement: PropTypes.func.isRequired,
    resetHandlebarPosition: PropTypes.func.isRequired,
    currentProject: PropTypes.object, // eslint-disable-line
};

View.defaultProps = {
    svgString: null,
};

export default View;

**Comment by nufaylr** [comment]
Hi Christian, I was exploring this. By adding as inclusion under image src will lose the SVG tree instead will be loaded as file. in my case i wanted to attach some event listeners to some group tags etc,..

also xlink:href is deprecated can be used as **href** instead.

**Comment by chrvadala** [comment]
Can I ask you, how are you adding that extra listener on those nodes? Are you using plain javascript or the React way?

**Comment by nufaylr** [comment]
Currently doing in a plan Javascript way 😞, but i wanted to move into React way. I came across this module [https://www.npmjs.com/package/react-svgmt](react-svgmt). Looks promising and SVG parsing.

In Addition your [https://github.com/chrvadala/react-svg-pan-zoom/issues/130#issuecomment-453605799](suggested idea) might need to change bit like this :

` <ReactSvgPanZoomLoader src="image.svg" render= {(width, height, content) => (
    <ReactSVGPanZoom width={500} height={500}>
             <svg width={width} height={height}>
                  {content}
             </svg>  
       </ReactSVGPanZoom>
)}/>`

Some resources [https://reactjs.org/docs/render-props.html](Render Props) , [https://americanexpress.io/faccs-are-an-antipattern/](FaCCs as antipattern)

**Comment by chrvadala** [comment]
Thanks for your PR. Since this implementation requires an external dependency I was wondering if it is better to release it as a different package. Thought?

**Comment by nufaylr** [comment]
Yes sounds good. So Adding as packages folder in the root?

**Comment by chrvadala** [comment]
I was evaluating three different options: 
1. Restructure the entire repo and create two folders /react-svg-pan-zoom and /react-svg-pan-zoom-loader
2. Use Lerna
3. Create a new repo

About Lerna I used it here https://github.com/chrvadala/react-refactor and honesty I don't like it :)
For the other alternative probably create a new repo, could be the better way

**Comment by chrvadala** [comment]
For new repo I mean a new GitHub repo. This makes more easy to maintain this new project.
I'll create this new repo late this day. If you want, I can share with you the project maintenance.

**Comment by nufaylr** [comment]
Yes Sounds good, Happy to get involved in.. 👍

**Comment by nufaylr** [comment]
Hi @chrvadala , Many thanks. I have accepted the request, it's a private repo, any reason to keep it private?

**Comment by chrvadala** [comment]
I'll publish it as soon as we have a first running version. Hope that isn't a problem ;-)

**Comment by chrvadala** [comment]
A new library has been built. It's available here https://github.com/nufaylr/react-svg-pan-zoom-loader
