### ISSUE TITLE
Question: How can I add dynamically an svg ?

### ISSUE THREAD

**Issue by levaifelasticad** [chrvadala/react-svg-pan-zoom#132]
I tried with this syntax:

render() {
        return (
            <div className={styles.stageCurrentFrame}>
                <div
                    // eslint-disable-next-line
                    onClick={this.onStageClick}
                    role="presentation"
                >
                    <ReactSVGPanZoom
                        dangerouslySetInnerHTML={{
                            __html: this.props.svgString,
                        }}
                        width={500}
                        height={500}
                        detectAutoPan={false}
                        toolbarPosition={'left'}
                        miniaturePosition={'left'}
                    />
                </div>
            </div>
        );
    }

where this.props.svgString is a string containing an svg file content.

**Comment by guy-at-ttt** [comment]
Did you find a solution for this? I tried to do a similar thing but i ended up "lagging" the page with every update.

**Comment by chrvadala** [comment]
Yes, there's is a subproject (relative new) here https://github.com/nufaylr/react-svg-pan-zoom-loader
