### ISSUE TITLE
change toolbar's icons

### ISSUE THREAD

**Issue by levaifelasticad** [chrvadala/react-svg-pan-zoom#134]
Hi,

Is there a possibility to change the icons in toolbar ?

**Comment by chrvadala** [comment]
You can't directly change the icons, but there's a property to provide a custom toolbar.

Just copy and paste this https://github.com/chrvadala/react-svg-pan-zoom/blob/master/src/ui-toolbar/toolbar.jsx and make your changes


https://github.com/chrvadala/react-svg-pan-zoom/blob/master/docs/documentation.md#available-props

**Comment by chrvadala** [comment]
I'm going to close this issue. Feel free to open it again.
