### ISSUE TITLE
Loading SVG from component using create-react-app

### ISSUE THREAD

**Issue by andrewleith** [chrvadala/react-svg-pan-zoom#145]
I am loading my SVGs as components as per the CRA docs:
```
import { ReactComponent as FloorPlan } from "../../images/floorplan.svg";
```

When I try to use the `<FloorPlan />` component inside of `<ReactSVGPanZoom>` I get the some errors and no SVG is displayed.  If I copy the contents of `floorplan.svg` directly it works just fine.  Can someone tell me what I'm doing wrong?

Thanks!

**Comment by chrvadala** [comment]
If you want to dynamically load a SVG content, you have to use this external dependency https://github.com/nufaylr/react-svg-pan-zoom-loader
