### ISSUE TITLE
Typescript types missing for V3

### ISSUE THREAD

**Issue by gorgi** [chrvadala/react-svg-pan-zoom#155]
### Features:
Hi and thanks for this awesome library. 
Is there any plan for introducing types for version 3?

**Comment by gorgi** [comment]
Thanks for replying @chrvadala .

Those types are for version 2. These migrations have not been implemented in the type definitions: https://github.com/chrvadala/react-svg-pan-zoom/blob/master/docs/migrate-from-v2-to-v3.md

As you can see here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-svg-pan-zoom/index.d.ts

- the Value field is nullable, but in version 3 it is required
- miniature and toolbar props have not been migrated
- and other things making it impossible to compile the component.

**Comment by chrvadala** [comment]
You're right... Sorry, but I don't use ts 
Can you try to contact https://github.com/huy-nguyen that is the maintenair of the ts descriptor?

**Comment by huy-nguyen** [comment]
I don't use the library anymore but nevertheless opened a PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39085.

**Comment by gorgi** [comment]
That is great, thanks @huy-nguyen

**Comment by chrvadala** [comment]
Thanks @huy-nguyen 🚀
