### ISSUE TITLE
Scale factor min bug - unable to set zoom value to specified minimum value 

### ISSUE THREAD

**Issue by wolasss** [chrvadala/react-svg-pan-zoom#161]
Hi, thanks for all the work you did in the library, it works really nice. 

I found a little bug I think, please consider this example: 

https://jsfiddle.net/546yqbzk/ 

You have two function, _zoomIn()_ - zooms the viewer by the scale of **1.25** and _zoomOut()_ that scales the viewer by the factor of **1 / 1.25** (0.8). 

So from my understanding, if I set a scaleFactorMin to 1, it would let the value of zoom to equal one. So if I click on the **zoom in** button once and then **zoom out** once I would expect the viewer to come back to the same position since 1.25 * 0.8 = 1. Unfortunetely it doesnt work as expected. It does not come back to zoom value of 1. 

I think the problem lies in the https://github.com/chrvadala/react-svg-pan-zoom/blob/b92c6cee0d7945073e6bc4f9255af85b4b2fa656/src/features/zoom.js#L10

function _lessThanScaleFactorMin_ actually checks if the calculated value is LESS OR EQUAL, hence it stops from setting the value equal to scaleFactorMin.

**Comment by chrvadala** [comment]
I did few tests and I agree with you, both `lessThanScaleFactorMin` and `moreThanScaleFactorMax` codes have to be replaced with a STRICT COMPARE operator. I'll release a fix in a couple day, in the meantime a rapid workaround is to sum (or substract) an EPSILON
```
 scaleFactorMin={1 - Number.EPSILON}
```

**Comment by chrvadala** [comment]
Fixed with 3.6

**Comment by wolasss** [comment]
Perfect, thanks!
