### ISSUE TITLE
Regression in 3.7.0: setPointOnViewerCenter no longer centers viewer on point

### ISSUE THREAD

**Issue by yann-combarnous** [chrvadala/react-svg-pan-zoom#169]
### Bug reports:
When trying to center and zoom on point that was clicked, 3.7.0 introduced a regression compared to 3.6.0 and below.

Steps to reproduce:
- on the 2 links below, click several times on points on the charts
- vs 3.7.0 will not center the chart on the point being clicked, version 3.6.0 will

Fiddle links to reproduce:
- 3.7.0: https://jsfiddle.net/9coq81za/1/
- 3.6.0: https://jsfiddle.net/9coq81za/2/

**Comment by yann-combarnous** [comment]
Looking further into it, ViewerMouseEvent provides correct (x,y) coordinates on first click, and wrong ones for second onward.

**Comment by chrvadala** [comment]
Fixed with 3.7.1
