### ISSUE TITLE
tool={"auto"} invalid? 

### ISSUE THREAD

**Issue by Lwuun** [chrvadala/react-svg-pan-zoom#17]
Hello! I am trying to put the tool on auto (as a fixed tool setting), but it throws me this warning:

> Failed prop type: Invalid prop `tool` of value `auto` supplied to `ReactSVGPanZoom`, expected one of ["none","pan","zoom-in","zoom-out"].

Should I be calling up
 
`tool={"auto"}`

differently?

**Comment by chrvadala** [comment]
Hi @Lwuun,
I have just tested the tool auto and I haven't any problem. I have also checked React prop types config and it's right.
https://github.com/chrvadala/react-svg-pan-zoom/blob/master/src/viewer.js#L357

Are you using the latest version of this component? Consider that this feature has been released with the version 2.2.0.

Let me know

**Comment by Lwuun** [comment]
Ah, that was the problem! I indeed had version 2.1.1. Thanks so much for your quick response!

**Comment by chrvadala** [comment]
You're welcome!
