### ISSUE TITLE
Autosizer example outdated / not working

### ISSUE THREAD

**Issue by Ali-Ozturk** [chrvadala/react-svg-pan-zoom#188]
### Bug reports:
The provided example of using AutoSizer to automatically adjust width and heigth is not working. I've tried creating an identical example without luck.

https://github.com/chrvadala/react-svg-pan-zoom/blob/master/docs/autosizer-viewer.md
https://codesandbox.io/s/autosizer-react-svg-pan-zoom-issue-newbu

Would love for this to work or perhaps a solution for such use cases

**Comment by chrvadala** [comment]
You can find an updated example here https://github.com/chrvadala/react-svg-pan-zoom/blob/d276914a98ba41074d944558afbdb74709d74bcd/storybook/stories/StandardViewer.stories.jsx#L295-L319

This snippet is part of a Pull Request that I'll complete and merge in the following weeks
