### ISSUE TITLE
Members required for customized toolbar are not exported

### ISSUE THREAD

**Issue by justin-hackin** [chrvadala/react-svg-pan-zoom#191]
### Bug reports:

One can not follow the instructions provided here https://github.com/chrvadala/react-svg-pan-zoom/issues/134 for customizing toolbar because the toolbar code contains imports relative to the src directory of this project. This requires obscure workarounds so that the dependent project can build the source files of this project. 

### Features:

Although TOOL_PAN, TOOL_ZOOM_IN, TOOL_ZOOM_OUT, and fitToViewer are exported, ToolbarButton and the icons are not. A simple solution: export ToolbarButton and icon components.

**Comment by justin-hackin** [comment]
Here's a PR https://github.com/chrvadala/react-svg-pan-zoom/pull/192

However, you might want to consider enabling custom icons as props since I think this is the most common use case and having to copy-paste the existing code is not DRY.  Though, in my use case, I also wanted to remove the none tool and props could be provided for this as well.

**Comment by chrvadala** [comment]
PR released with v3.9.0

**Comment by justin-hackin** [comment]
Thanks again for accepting the PR.  You helped me to build this https://www.youtube.com/watch?v=_J6QBTSfmpU

**Comment by chrvadala** [comment]
Wow, your lanterns are awesome and great use of the pan zoom tool!
Thanks for sharing
