### ISSUE TITLE
defaultProps deprecation warning in React 18.3

### ISSUE THREAD

**Issue by davefallis** [chrvadala/react-svg-pan-zoom#224]
`Warning: Toolbar: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

I am assuming this library won't work in React 19, which will (presumably) be coming out soon.

**Comment by aniket-xcentium** [comment]
I am also getting same warning.

**Toolbar: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.**

Did you got any solution for this ?

**Comment by chrvadala** [comment]
Hi guys, I'm going to release a new version that fixes this issue

**Comment by chrvadala** [comment]
Fix release with 3.13.1
