### ISSUE TITLE
Component zoom API method inconsistent

### ISSUE THREAD

**Issue by hamfz** [chrvadala/react-svg-pan-zoom#24]
When using the component .zoom or .zoomOnViewerCenter, is there a way to ensure that the resulting scaling is consistent?

For example if you were you call zoomOnViewerCenter(0.9) followed by zoomOnViewerCenter(1.1), then call both methods again, you will continually move the zoom range window "outward".

Attached a screenshot of an example console output from the above test. 

<img width="286" alt="screen shot 2017-02-20 at 3 56 29 pm" src="https://cloud.githubusercontent.com/assets/742773/23144487/2b149084-f785-11e6-8510-095fb248842f.png">

The second number represents the value returned from component.getValue().a

**Comment by chrvadala** [comment]
I guess that I hava just solved this issue (branch fix-scale-factor). Could you try this new version (not yes released)? 
`"react-svg-pan-zoom": "chrvadala/react-svg-pan-zoom#30804bcfbf13e2c06c00bb1b1105f0cd21bd3b31"`

**Comment by chrvadala** [comment]
fixed with 2.5
