### ISSUE TITLE
Typescript typings file should declare `background` prop as string

### ISSUE THREAD

**Issue by spcfran** [chrvadala/react-svg-pan-zoom#35]
The [typings file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-svg-pan-zoom/index.d.ts) for this project defines `background` prop as type `React.CSSProperties`. It should be `string`.

Apologies for raising the issue here and not in the DefinitelyTyped project but i'm not sure who maintains the typings file or how to contribute there

**Comment by chrvadala** [comment]
Thanks @spcfran for your support.
I didn't know DefinitelyTyped, but I've just pull requested a fix. I guess that we have to wait @huy-nguyen  review
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16143#issuecomment-297399371
