### ISSUE TITLE
Add prop fitToViewerOnMount

### ISSUE THREAD

**Issue by chrvadala** [chrvadala/react-svg-pan-zoom#37]

**Comment by chrvadala** [comment]
This feature is not really necessary and can be replaced by 
```
componentDidMount() {
    this.Viewer.fitToViewer();
}
```

**Comment by verner-lall** [comment]
Sorry but how can I use this? I use the component in a modal, the svg gets generated when the modal is opened and I want to fit it to viewer. I think it is a necessary prop.

**Comment by verner-lall** [comment]
Thanks!
