### ISSUE TITLE
Generic mouse event callbacks for Toolbar

### ISSUE THREAD

**Issue by brentoneill** [chrvadala/react-svg-pan-zoom#38]
Just thought these might be nice to have. In our implementation, we would like to know when a user clicks the toolbar so that we can show some messaging or tooltip popup.

So maybe we could add:
 `onClick`, `onMouseEnter`, `onMouseLeave`, `onMouseOver` ?

**Comment by chrvadala** [comment]
Yes, this should be very useful together with already available feature  `customToolbar`.
