### ISSUE TITLE
Miniature height ratio when user defined different svg width and svg height

### ISSUE THREAD

**Issue by chenershuile** [chrvadala/react-svg-pan-zoom#40]
I tends to make rectangle svg which the width is large than the height。However , i found that when using the default settings, I got a miniature which has a width less than height.
I check the code in lib/ui-miniature/miniature.js and found : 
 var SVGWidth = value.SVGWidth,
      SVGHeight = value.SVGHeight,
      viewerWidth = value.viewerWidth,
      viewerHeight = value.viewerHeight;
  var ratio = SVGWidth / SVGHeight;
  var miniatureHeight = miniatureWidth * ratio;

It seems you may mis calculate the ratio? I think it should be 
ratio = SVGHeight/SVGWidth.

May be i have make a mistake of this code.

**Comment by chrvadala** [comment]
Fixed with 2.8.0
Thanks!
