### ISSUE TITLE
Prevent zoom on double click

### ISSUE THREAD

**Issue by jessemull** [chrvadala/react-svg-pan-zoom#42]
I don't seem to be able to prevent a zoom when I double click. Is there a way to disable it. Setting the onDoubleClick prop is not working for me. Thanks.

**Comment by chrvadala** [comment]
Hi @jessemull,
I suppose that you are using the tool `auto`.
Sorry, but at this moment there isn't an option to disable the zoom feature in auto mode. If you want to interact with the svg I suggest to select the tool `none` when required.

**Comment by otake** [comment]
Would you be open to a Pull Request on this? I need to fix this our app, so I'm going to do it regardless.

As I see it, there are 2 ways to solve this:
1) Add a new prop called `zoomOnDoubleClick`
2) add an `onDoubleClick` event handler on <ReactSVGPanZoom> and use event.preventDefault() to stop the zoom from happening.

Thoughts? Prefer one over the other?

**Comment by chrvadala** [comment]
A PR is absolutely accepted :D I guess that the first proposal is better, because I'm not sure which side effect could have with the second proposal.

About the name of the prop it doesn't show that it refer only to the tool auto. 
Can I suggest `disableZoomWithToolAuto` or something like this? 
A feature `disablePanWithToolAuto` should also be useful...

**Comment by otake** [comment]
PR https://github.com/chrvadala/react-svg-pan-zoom/pull/43

**Comment by jessemull** [comment]
@chrvadala Fantastic, I wasn't expecting such a rapid response. I was using auto and this would be a nice feature. I think I will just disable the double click locally and then pull in otake's PR when its merged. Thanks to you and everyone that helped to create such a great react component. Cheers, J.

**Comment by chrvadala** [comment]
Thanks @otake for your PR. ReactSVGPanZoom v2.10 is out
