### ISSUE TITLE
working with svg image received from server as data

### ISSUE THREAD

**Issue by dy10** [chrvadala/react-svg-pan-zoom#44]
My react app is receiving svg as response from an API call and it is currently rendered using below syntax

`<span dangerouslySetInnerHTML={{__html: this.state.data.image}} />`

I want to add pan-zoom features but not sure how to do it with this library. Could you please allow passing image data as props to this component or suggest any workarounds.

-thnx

**Comment by chrvadala** [comment]
React SVG Pan Zoom requires SVG size to work properly. You should at least parse the <SVG width="" height=""> definition and create an `<svg>` tag with that data.

```
<ReactSVGPanZoom ... >
    <svg width={parsedWidth} height={parsedHeight}  dangerouslySetInnerHTML={{__html: this.state.data.image}} 
</ReactSVGPanZoom ... >
```

I haven't tested it, but it should work. Let me know.

**Comment by dy10** [comment]
forked your jsfiddle with this change but it is not working. Please have a look at
  [https://jsfiddle.net/dy10/dnatL9bd/](https://jsfiddle.net/dy10/dnatL9bd/)

**Comment by chrvadala** [comment]
Solved! We can't set the inner html of the `<svg>` element, but we need a `<g>` element inside it.
https://jsfiddle.net/dnatL9bd/4/

```jsx
 var img = '<g><circle cx="108" cy="108.5" r="100" fill="#0ff" stroke="#0ff"/></g>'

class Example extends React.Component {
    render() {
        return (
            <ReactSVGPanZoom
        width={500} height={500}
        onClick={event => console.log(event.x, event.y, event.originalEvent)}>
  
        <svg width={500} height={500}>
          <g dangerouslySetInnerHTML={{__html: img}}/>
        </svg>  
      </ReactSVGPanZoom>
        );
    }
}
```

**Comment by dy10** [comment]
This works. Thanks a lot !

**Comment by chrvadala** [comment]
You're welcome

**Comment by lionkeng** [comment]
Hello @chrvadala , first of all, thanks for this great repo!

I am trying out the technique described here and I got it to work as advertised. However, the miniature feature looks has the SVG content translated to the top left corner and miniaturized to take up only a small fraction of the miniature view.

Would appreciate some help and pointers! thanks.

Here is a link to my repo:
https://github.com/lionkeng/test-react-svg-pan-zoom

Here is a screen shot of the problem.
<img width="1408" alt="screen shot 2018-02-12 at 5 03 56 pm" src="https://user-images.githubusercontent.com/1751072/36122459-635bca92-1017-11e8-8563-e4e269f0386a.png">

**Comment by KristianLonergan** [comment]
Hi @lionkeng,
Did you find a fix for the miniature feature not being correct ?

**Comment by lionkeng** [comment]
> Hi @lionkeng,
> Did you find a fix for the miniature feature not being correct ?

hi @KristianLonergan - I think we ended up not using the miniature feature at that point. That said, we were testing then with an older version of v2. Seems to be working now in another project where we are using this feature with v3.
