### ISSUE TITLE
How to pass viewBox or any other properties to svg element ?

### ISSUE THREAD

**Issue by LogicMonsters** [chrvadala/react-svg-pan-zoom#46]
It seems svg element will be replaced with a new one, all properties are gone. Is there a way to set a property on our own, like set a viewBox.

**Comment by chrvadala** [comment]
It's an architectural choice. I can't guarantee that this component works with some svg settings. 
Why do you need to set the viewBox? I guess that this is one of the primary props that could break the component 😄

**Comment by LogicMonsters** [comment]
Becasue only when viewBox and viewPort are both set correctly, the SVG could be rendered normally especially for large element which needs to be fit in a smaller viewPort. Since we could set the width and height, so the viewPort can be set, but when I pass in viewBox, it is gone, and then, what is left is a white background, since viewBox is removed from svg element.

**Comment by LogicMonsters** [comment]
What I am doing is, I accomodate the svg width and height to match viewBox size (which is very large number), and then call fitToViewer  in componentDidMount() to let the svg fit the viewer.

**Comment by chrvadala** [comment]
What you described is the right way to fit the image inside the Viewer (https://github.com/chrvadala/react-svg-pan-zoom/blob/master/examples/1-basic/src/App.js#L10-L12), but maybe that I'm not hitting the point. Could you publish a JSFiddle starting from here https://jsfiddle.net/chrvadala/f67qyfsd/?

**Comment by LogicMonsters** [comment]
So I set  <svg width={10240} height={7680} viewBox="0 0 10240 7680">, and now I have to hit "fit to viewer" button before I could see the polygons.  Because the property of "viewBox" is removed before it is rendered.

**Comment by LogicMonsters** [comment]
By the way, JS fiddle is updated now !

**Comment by chrvadala** [comment]
I see, but you don't need a button to call the fitToViewer action. You can use the componentDidMount callback. https://jsfiddle.net/f67qyfsd/13/

**Comment by LogicMonsters** [comment]
Yes, exactly, that is what I am doing in the project.

**Comment by chrvadala** [comment]
Ok, but it's the right way

**Comment by LogicMonsters** [comment]
Thanks !

**Comment by chrvadala** [comment]
You're welcome
