### ISSUE TITLE
Pinch-to-zoom disabled w/ detectWheel set to false

### ISSUE THREAD

**Issue by nerdgrass** [chrvadala/react-svg-pan-zoom#48]
Hey there! Thank you for this incredibly useful component, its been a huge help for a project I'm working on. I encountered a problem, though - When the primary component's props are set below, the pinch gesture works (on a macbook air's trackpad) as it does by default (zooming the whole page) instead of zooming just the SVG (on OSX, in updated chrome):
```js
<ReactSVGPanZoom 
  detectWheel={false}
  detectPinchGesture={true} />
```

This feels somewhat counter-intuitive at a minimum, but also makes it so that if you want pinch-to-zoom, you have to enable scroll-to-zoom, which doesn't work for the UX on my project. I'm currently investigating this issue, and if I can figure it out, I'll put up a PR, but wanted to see if anybody else had an answer/if anybody else encountered this bug.

**Comment by nerdgrass** [comment]
Yikes, I chased this down more and apparently I only thought I was enabling pinch to zoom in Chrome - its actually entirely controlled by scrolling and seems fairly inexorably linked to the `onWheel` event as there isn't a trackpad standard that I could find. Closing this because the problem most likely goes deeper into the library, though if I do happen to find a fix I'll happily post my solution

**Comment by chrvadala** [comment]
Unfortunately at this moment browsers haven't touchpad gestures support. Chrome emulates these events using the scroll event (`onWheel`). An alternative (not directly supported by this lib) is to use some extensions.
About the two props of this lib:
- `detectWheel` refers to scroll events
- `detectPinchGesture` refers to mobile pinch gesture

Hope that help
