### ISSUE TITLE
Export Miniature component

### ISSUE THREAD

**Issue by DmitriySpirit** [chrvadala/react-svg-pan-zoom#53]
When I want to define custom Miniature component based on existent Miniature from the tool, I can`t import it, but Toolbar I can. 
I have made a fork when diff is only export this Component like a Toolbar. Can you accept a pull request? #54

**Comment by chrvadala** [comment]
Sure, thanks for your PR

**Comment by chrvadala** [comment]
v2.12.0 just released.
@DmitriySpirit Now you are in the contributors list. Thanks
