### ISSUE TITLE
Touch events doesn't fire for children. 

### ISSUE THREAD

**Issue by vanthiyathevan** [chrvadala/react-svg-pan-zoom#59]
None of the touch events fire for child elements. Especially on iPad.

**Comment by nglgzz** [comment]
@vanthiyathevan did you solve this? I'm having the same problem

**Comment by vanthiyathevan** [comment]
@nglgzz I worked around the issue by wrapping this in my own component and pass children to it.

**Comment by chrvadala** [comment]
@vanthiyathevan We solved this problem here https://github.com/chrvadala/react-svg-pan-zoom/issues/61
