### ISSUE TITLE
callback for actions (zoom, pan)

### ISSUE THREAD

**Issue by hatpick** [chrvadala/react-svg-pan-zoom#60]
Are there any callbacks for onZoom, onPanactions or at least do we access to the current values for zoom, panX, panY?

**Comment by hatpick** [comment]
what are "a, b, c, d, e" in the "value"?

**Comment by chrvadala** [comment]
Hi @hatpick,
there is still an opened issue about this https://github.com/chrvadala/react-svg-pan-zoom/issues/30.
I hope to start to work on it very soon, but at this moment I haven't any target date.

To obtain some status information consider that onChangeValue callback gives back an object that contains few letters {a,b,c,d,e,f}. They refer to a transformation matrix. A transformation matrix describes zoom and pan status as standardized by w3c. 
To learn more about this argument see these resources:
- https://www.w3.org/TR/SVG/coords.html#TransformAttribute
- https://github.com/chrvadala/transformation-matrix

**Comment by hatpick** [comment]
Hello @chrvadala,

Thanks for your response. I can use onChangeValue and decompose the Value to get what I want. There is a minor bug for zooming out, the mode is always "idle" when I'm zooming out.

**Comment by chrvadala** [comment]
In progress in https://github.com/chrvadala/react-svg-pan-zoom/pull/71

**Comment by chrvadala** [comment]
In progress here https://github.com/chrvadala/react-svg-pan-zoom/pull/75

**Comment by chrvadala** [comment]
Introduced in version 2.16.0
