### ISSUE TITLE
Touch event not propagating to children

### ISSUE THREAD

**Issue by nglgzz** [chrvadala/react-svg-pan-zoom#61]
Hey, I want to use this component to enable pan and zoom on SVG maps. Everything works fine on desktop after some tweaking, however I can't get the touch event on mobile to be passed down to the children (there's links and buttons inside the maps). 

Is it possible with some props to enable the propagation of touch events?
Thank you.

**Comment by chrvadala** [comment]
Hi @nglgzz, which tool are you using? Consider that only the `none` tool enables child events.
Could you provide a jsfiddle that throws the problem? Here there is a skeleton https://jsfiddle.net/chrvadala/f67qyfsd/

**Comment by nglgzz** [comment]
I'm using the `pan` tool, so probably that's why. I checked again the docs and I noticed just now  that it says only `none` and `auto` enable child events. I think I tried with `auto` but it didn't work. I'll try again this evening and I'll post an update.

**Comment by nglgzz** [comment]
I tried again, and sure enough with `none` touch events are propagating. I then changed to `auto`, but that works only on desktop, not on mobile. Here's the updated jsfiddle https://jsfiddle.net/f67qyfsd/21/  

In case this is expected behavior, is there the possibility to have a new prop for enabling event propagation? I need panning, but at the same time I need people to be able to click/tap links and buttons 😄 

I can try this myself and submit a pull request if you can give me some guidance on how to build the project.

**Comment by chrvadala** [comment]
The jsfiddle that you provided me doesn't respect w3c constraints. You can't have html elements nested in a SVG
I replaced it with a compliant version and it seems to work.
https://jsfiddle.net/f67qyfsd/28/ 
Let me know

**Comment by nglgzz** [comment]
Yes you can have HTML elements inside an SVG, that's the whole point of having a foreignObject tag.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

The updated version works in the sense that it renders the text, but as I said I need links and buttons. This is what I'm trying to achieve: 
http://dev.learn-anything.xyz/803
 
That version is using D3 for rendering the SVG and it's working as expected. However in the update I'm working on I had to rewrite the component so it's rendered entirely with React. This is where react-svg-pan-zoom comes into play, cause I couldn't find any other library doing pan and zoom in the way I need/want it. The only problem is that on mobile I can't tap links or buttons, while everything else works fine.

**Comment by chrvadala** [comment]
I didn't know that SVG feature, thanks for letting me know.

I think that the problem with links and buttons on mobile is caused by preventDefault that I call in a lot of point to avoid browser behaviours. 
I also found that each mouse related callback like onClick, onMouseDown,... isn't anytime call.

To perform an action on mobile you could use touch events that are correctly handled. Probably you have to provide an alternative version for each button and link that uses touch callback to handle an event
As alternative you could remove the preventDefault, but I think that it isn't safe because I remember that in a lot of situation the browser follow strange behaviour.

I made a new jsfiddle https://jsfiddle.net/f67qyfsd/30/

Hope that it's useful

**Comment by nglgzz** [comment]
No problem 👍 

Okay seems like that should do the trick, I'm gonna try it this evening and I'll post an update.

Thank you

**Comment by nglgzz** [comment]
Awesome!! That worked 🎉 

Thank you a bunch for the help

**Comment by chrvadala** [comment]
Great! Feel free to add your project in README
https://github.com/chrvadala/react-svg-pan-zoom#some-projects-using-react-svg-pan-zoom

**Comment by nglgzz** [comment]
Sure thing! Will make a PR as soon as we release the new version :)
