### ISSUE TITLE
Ability to set Mouse wheel zoom speed

### ISSUE THREAD

**Issue by vanthiyathevan** [chrvadala/react-svg-pan-zoom#62]
Is there any way to change the zoom speed on mouse wheel?

**Comment by auroranil** [comment]
There is a prop called `scaleFactor` (see [React SVG Pan Zoom - documentation](https://github.com/chrvadala/react-svg-pan-zoom/blob/master/docs/documentation.md#props)), but it seems that it does not make use of that prop at all.

**Comment by chrvadala** [comment]
Hi @auroranil,
could you provide some example?

**Comment by vanthiyathevan** [comment]
I see that it is not using the `scaleFator`
Currently it is hardcoded
https://github.com/chrvadala/react-svg-pan-zoom/blob/99af93d245b33d8bab70040061d3bb48087577f7/src/features/interactions.js#L166

**Comment by chrvadala** [comment]
Thanks for letting me know. I will fix it asap

**Comment by auroranil** [comment]
Using prop `scaleFactorOnWheel`, the mouse wheel zoom speed can be set to any value. See https://github.com/chrvadala/react-svg-pan-zoom/pull/63#issuecomment-349107375 for more information.

This issue has been resolved.

**Comment by chrvadala** [comment]
Released with v2.14
