### ISSUE TITLE
Removing map from multimap page break other minimaps

### ISSUE THREAD

**Issue by xCMNx** [chrvadala/react-svg-pan-zoom#74]
Hello, sorry for my english.
The problem is that minimap mask is not unique, and when last (maybe not last) created map is removed, then all other minimaps didn't respond to changes on their map, we fix that problem by adding the property to the map (like mapIndex), and when mask is creating we add the index to the mask name

**Comment by chrvadala** [comment]
Hi man,
thanks for your issue. 
To fix it, I need an example that shows the problem.
Could you provide it, using this jsfiddle as base? https://jsfiddle.net/chrvadala/f67qyfsd/
Let me know

**Comment by xCMNx** [comment]
here https://jsfiddle.net/f67qyfsd/47/ 
looks like only first map controll mask

**Comment by chrvadala** [comment]
Thanks for your jsfiddle. I improved a bit your example (https://jsfiddle.net/f67qyfsd/49/), but there's still that error. 
I'll release a fix soon.

Thanks

**Comment by chrvadala** [comment]
Fixed with 2.15.1
