### ISSUE TITLE
ScaleFactorMin does not work

### ISSUE THREAD

**Issue by eMarek** [chrvadala/react-svg-pan-zoom#77]
I've figured it out that scaleFactorMin does not work. With not working I mean that I can zoom out much more that the set scale value. Not sure if this is known bug or not. First I thought it is related to selected tool, but after more testing I found out it is not related to tools. Anyone with the same issue?

**Comment by chrvadala** [comment]
I didn't find a way to replicate it. Could you provide and example that shows the bug?
Please fork this jsfiddle https://jsfiddle.net/chrvadala/f67qyfsd/

**Comment by eMarek** [comment]
Here: https://jsfiddle.net/7ppbhh7o/1/
Only change which I made is added `scaleFactorMin={0.5}` on line 7.
It should stop me from zooming out at some point I suppose, but I can make it super small.

<img width="1327" alt="screen shot 2018-02-13 at 14 54 19" src="https://user-images.githubusercontent.com/311634/36153236-df092340-10cd-11e8-867f-fb304f64aeda.png">

**Comment by eMarek** [comment]
Have you been able to reproduce my issue?

**Comment by chrvadala** [comment]
I can confirm that it is a bug. On init boundaries aren't well initialised.
I found a temporary workaround https://jsfiddle.net/7ppbhh7o/9/
I'll fix it soon

**Comment by eMarek** [comment]
Thank you very much! Let me know when fix will be on npm.

**Comment by chrvadala** [comment]
Fixed with 2.16.0
