### ISSUE TITLE
ref on svg element 

### ISSUE THREAD

**Issue by abonec** [chrvadala/react-svg-pan-zoom#78]
Example here 
https://jsfiddle.net/abonec/nx0sb3dx/3/ 
I added ref callback to svg element which I use to draw using d3 on svg. But when I wrap svg in ReactSVGPanZoom in will not happen.

**Comment by chrvadala** [comment]
Because of this https://github.com/chrvadala/react-svg-pan-zoom/blob/master/src/viewer.js#L249-L253
The viewer uses a new SVG tag to render its children comps and so the ref prop isn't copied.

**Comment by abonec** [comment]
Is it possible to get svg node to draw on it in the same manner?

**Comment by abonec** [comment]
I got an answer: `ref = {node => this.drawBoxes(node.ViewerDOM)}` on `ReactSVGPanZoom`

**Comment by abonec** [comment]
But if I dynamically add elements by d3 zoom did not work.
https://jsfiddle.net/abonec/nx0sb3dx/5/

**Comment by chrvadala** [comment]
Fixed https://jsfiddle.net/nx0sb3dx/6/ but unfortunately miniature can't work in this way.
