### ISSUE TITLE
Multiple instance of react-svg-pan-zoom and miniature

### ISSUE THREAD

**Issue by samy14** [chrvadala/react-svg-pan-zoom#80]
If I use multiple instances of  svg-pan-zoom the zoom and pan on the first instance control the miniatures of others

**Comment by chrvadala** [comment]
Can you publish a jsfiddle based on this https://jsfiddle.net/chrvadala/f67qyfsd/ that shows the issue?

**Comment by chrvadala** [comment]
@samy14 I close this issue, If you need support feel free to open it again
