### ISSUE TITLE
Failed prop type: should have a single child of the following types:  svg

### ISSUE THREAD

**Issue by alcalyn** [chrvadala/react-svg-pan-zoom#84]
I'm ok with the fact that we must use `<ReactSVGPanZoom>` component with a `<svg>` children:

``` html
<ReactSVGPanZoom>
    <svg>
    </svg>
</ReactSVGPanZoom>
```

But I'm using a component as a `<svg>` wrapper:

``` html
<ReactSVGPanZoom>
    <HexGrid>
    </HexGrid>
</ReactSVGPanZoom>
```

It is working: it does not break the application. But I'm getting the following JS warning:

```
Warning: Failed prop type: `t` should have a single child of the following types:  `svg`.
```

And it break test suites.

I'm using this library: https://github.com/Hellenic/react-hexgrid
and this component https://github.com/Hellenic/react-hexgrid/blob/master/src/HexGrid.js#L24-L31

Should we consider using a react component that renders an `<svg>` element at top level is ok ?

https://github.com/chrvadala/react-svg-pan-zoom/blob/v2.16.0/src/viewer.js#L534-L552

**Comment by chrvadala** [comment]
I'm not sure that I can just change the validator. I understand that it works in your case, but I think that it won't work in general.
Actually this component uses the provided `svg` element to extract `width`, `height` and svg `children`. It uses these parameters to make a **new** `svg` component that replaces the provided one and customizes the behaviour to support pan and zoom feature.
In these lines there is what I'm telling:

https://github.com/chrvadala/react-svg-pan-zoom/blob/9ec05785c8f63af7e8b99b83bdec0f3538254417/src/viewer.js#L262-L266
https://github.com/chrvadala/react-svg-pan-zoom/blob/v2.16.0/src/viewer.js#L58

It should be great to limit validation to nodes that renders as `<svg>`, but I think that there isn't a way to detect what kind of element a component wants to render.

**Comment by alcalyn** [comment]
Ok, so in fact, we could assume that `<ReactSVGPanZoom>` waits for an element that has *at least* a `width` and `height` attributes to work, like an interface.

In example, I can replace `<svg width={617} height={316}>` by `<div width={617} height={316}>`: https://jsfiddle.net/f67qyfsd/116/ :D
