### ISSUE TITLE
No support for svg viewbox

### ISSUE THREAD

**Issue by kheyse-oqton** [chrvadala/react-svg-pan-zoom#86]
### Bug report/Feature request:
Svg viewbox is ignored.
Expect the document/white rectangle in the reactsvgpanzoom element to match the viewbox, but it doesn't.
<svg width={617} height={316} viewBox="40 40 80 80">
https://jsfiddle.net/oyLfjeqy/9/

**Comment by rajb4y** [comment]
Temporary solution to repeat the svg tag, so when component strips the first svg header still second svg will have viewbox on it.

**Comment by TimVanMourik** [comment]
I updated @kheyse-oqton's PR #88 to be up-to-date with current version in #150.

**Comment by TimVanMourik** [comment]
Now you can support this Wish from https://beerpay.io/chrvadala/react-svg-pan-zoom/wishes/5d66366510d9080d4ad89ffa

🍻 Cheers!

**Comment by chrvadala** [comment]
Released with version 3.3.0
